name: test mysql8
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: test mysql8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: test mysql8
        env:
          TEST_MYSQL_HOST: mysql8
          TEST_MYSQL_CHARSET: utf8mb4
          TEST_MYSQL_DBNAME: xorm_test
          TEST_MYSQL_USERNAME: root
          TEST_MYSQL_PASSWORD:
        run: TEST_CACHE_ENABLE=true make test-mysql

    services:
      mysql8:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: xorm_test
        ports:
          - 3306:3306