name: test mysql
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test-mysql:
    name: test mysql
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: test mysql utf8mb4
        env:
          TEST_MYSQL_HOST: mysql
          TEST_MYSQL_CHARSET: utf8mb4
          TEST_MYSQL_DBNAME: xorm_test
          TEST_MYSQL_USERNAME: root
          TEST_MYSQL_PASSWORD:
        run: TEST_QUOTE_POLICY=reserved make test-mysql-tls

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: xorm_test
        ports:
          - 3306:3306